{{- range .Values.services }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .name }}
  namespace: {{ $.Values.namespace.name }}
  labels:
    app.kubernetes.io/name: {{ .name }}
    app.kubernetes.io/part-of: cavendish
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: {{ .name }}
  ports:
    - name: http
      port: {{ .port }}
      targetPort: http
      protocol: TCP
{{- end }}
---
{{- if .Values.postgresql.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: {{ .Values.namespace.name }}
  labels:
    app.kubernetes.io/name: postgres
    app.kubernetes.io/part-of: cavendish
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    app.kubernetes.io/name: postgres
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
    - name: metrics
      port: 9187
      targetPort: metrics
{{- end }}
