{{- range .Values.services }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .name }}
  namespace: {{ $.Values.namespace.name }}
  labels:
    app.kubernetes.io/name: {{ .name }}
    app.kubernetes.io/part-of: cavendish
  {{- if .irsa.enabled }}
  annotations:
    eks.amazonaws.com/role-arn: {{ .irsa.roleArn | quote }}
  {{- end }}
automountServiceAccountToken: true
{{- end }}
---
{{- if .Values.postgresql.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: postgres
  namespace: {{ .Values.namespace.name }}
  labels:
    app.kubernetes.io/name: postgres
    app.kubernetes.io/part-of: cavendish
  annotations:
    eks.amazonaws.com/role-arn: {{ .Values.postgresql.backup.irsaRoleArn | quote }}
{{- end }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: pg-backup
  namespace: {{ .Values.namespace.name }}
  labels:
    app.kubernetes.io/name: pg-backup
    app.kubernetes.io/part-of: cavendish
  annotations:
    eks.amazonaws.com/role-arn: {{ .Values.postgresql.backup.irsaRoleArn | quote }}
